FROM php:8.2-cli
WORKDIR /var/www
COPY . .
RUN apt-get update && apt-get install -y libzip-dev unzip default-mysql-client \
    && docker-php-ext-install zip pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
RUN composer install
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 8004

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
